In [14]:
import os

print(os.listdir("../data"))

['decisions.csv', 'disruptions.csv', 'inventory.csv', 'orders.csv', 'outcomes.csv', 'products.csv', 'shipments.csv', 'shipments_cleaned.csv', 'suppliers.csv']

In [13]:
shipments.to_csv("../data/shipments_cleaned.csv", index=False)

In [11]:
df.describe()

,shipment_id,supplier_id_x,product_id,shipment_date,expected_arrival,actual_arrival,quantity,lead_time,rating,unit_price,supplier_id_y
count,4000.000000,4000.000000,4000.000000,4000,4000,4000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,2000.500000,10.512500,74.879000,2025-07-13 20:43:04.800000,2025-07-19 20:47:45.600000,2025-07-21 10:13:48,255.323250,5.630638,4.191772,2596.565493,10.234500
min,1.000000,1.000000,1.000000,2024-07-15 00:00:00,2024-07-18 00:00:00,2024-07-17 00:00:00,10.000000,1.000000,3.500000,160.420000,1.000000
25%,1000.750000,6.000000,36.750000,2025-01-17 00:00:00,2025-01-22 00:00:00,2025-01-24 00:00:00,132.000000,2.760000,3.720000,1310.640000,5.000000
50%,2000.500000,10.000000,75.000000,2025-07-10 00:00:00,2025-07-16 00:00:00,2025-07-18 00:00:00,258.500000,5.830000,4.300000,2602.930000,10.000000
75%,3000.250000,15.000000,112.000000,2026-01-08 00:00:00,2026-01-14 00:00:00,2026-01-16 00:00:00,376.250000,8.090000,4.610000,3934.860000,15.000000
max,4000.000000,20.000000,150.000000,2026-07-15 00:00:00,2026-07-25 00:00:00,2026-07-29 00:00:00,500.000000,9.750000,4.880000,4929.240000,20.000000
std,1154.844867,5.733896,43.367171,NaN,NaN,NaN,142.179063,2.617774,0.469679,1443.559403,5.879554

In [10]:
df = shipments.merge(
    suppliers,
    on="supplier_id"
)

df = df.merge(
    products,
    on="product_id"
)

In [9]:
shipments["shipment_date"] = pd.to_datetime(shipments["shipment_date"])

shipments["expected_arrival"] = pd.to_datetime(shipments["expected_arrival"])

shipments["actual_arrival"] = pd.to_datetime(shipments["actual_arrival"])

In [8]:
shipments["actual_arrival"] = shipments["actual_arrival"].fillna("Pending")

In [7]:
shipments.drop_duplicates(inplace=True)

In [5]:
shipments.isnull().sum()

shipment_id         0
supplier_id         0
product_id          0
shipment_date       0
expected_arrival    0
actual_arrival      0
quantity            0
shipment_status     0
dtype: int64

In [4]:
shipments.head()

shipments.info()

shipments.describe()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   shipment_id       4000 non-null   int64
 1   supplier_id       4000 non-null   int64
 2   product_id        4000 non-null   int64
 3   shipment_date     4000 non-null   str
 4   expected_arrival  4000 non-null   str
 5   actual_arrival    4000 non-null   str
 6   quantity          4000 non-null   int64
 7   shipment_status   4000 non-null   str
dtypes: int64(4), str(4)
memory usage: 250.1 KB

       shipment_id  supplier_id   product_id     quantity
count  4000.000000  4000.000000  4000.000000  4000.000000
mean   2000.500000    10.512500    74.879000   255.323250
std    1154.844867     5.733896    43.367171   142.179063
min       1.000000     1.000000     1.000000    10.000000
25%    1000.750000     6.000000    36.750000   132.000000
50%    2000.500000    10.000000    75.000000   258.500000
75%    3000.250000    15.000000   112.000000   376.250000
max    4000.000000    20.000000   150.000000   500.000000

In [3]:
import pandas as pd

shipments = pd.read_csv("../data/shipments.csv")
products = pd.read_csv("../data/products.csv")
suppliers = pd.read_csv("../data/suppliers.csv")
inventory = pd.read_csv("../data/inventory.csv")
orders = pd.read_csv("../data/orders.csv")
disruptions = pd.read_csv("../data/disruptions.csv")
decisions = pd.read_csv("../data/decisions.csv")
outcomes = pd.read_csv("../data/outcomes.csv")

print(shipments.head())

   shipment_id  supplier_id  product_id shipment_date expected_arrival  \
0            1            6          29    2025-06-03       2025-06-07
1            2            7          84    2025-06-16       2025-06-26
2            3            9         119    2026-03-17       2026-03-23
3            4            5         140    2025-04-20       2025-04-23
4            5           18          56    2025-11-20       2025-11-23

  actual_arrival  quantity shipment_status
0     2025-06-12        16      In Transit
1     2025-06-24       106         Delayed
2     2026-03-24       325      In Transit
3     2025-04-28       419       Cancelled
4     2025-11-28       136         Delayed

In [2]:
import os
print(os.getcwd())

c:\Users\Hp\OneDrive\Documents\GitHub\SupplyPrescript\notebooks